python plotter.py --dir ../analysis_MuTau_10Mar_lims/ --var MT2  --sel s2b0jresolvedMcutlmr70 --channel MuTau --bcateg bb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log --xmax 500 --ymin 1.e-5 --ymax 800   --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_MuTau_10Mar_lims/ --var MT2  --sel s1b1jresolvedMcutlmr70 --channel MuTau --bcateg bj --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log --xmax 500 --ymin 1.e-5 --ymax 2000  --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_MuTau_10Mar_lims/ --var MT2  --sel sboostedLLMcut         --channel MuTau --bcateg bstbb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log --xmax 500 --ymin 1.e-4 --ymax 100  --tab --SRtype nonres --postfit --quit

python plotter.py --sigscale 10. --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcutlmr90 --channel MuTau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "  --ymin 5.e-3 --xmax 1000 --log --tab --SRtype resLM --postfit --quit
python plotter.py --sigscale 10. --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcutlmr90 --channel MuTau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "  --ymin 5.e-3 --xmax 1000 --log --tab --SRtype resLM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcuthmr90 --channel MuTau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 5.e-3 --xmax 1000 --log --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcuthmr90 --channel MuTau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 2.e-2 --xmax 1000 --ymax 80 --log --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel sboostedLLMcut    --channel MuTau --bcateg bstbb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 1.e-3 --ymax 500 --xmax 1000 --log --tab --SRtype resHM --postfit --quit


python plotter.py --dir ..//analysis_ETau_10Mar_lims/ --var MT2  --sel s2b0jresolvedMcutlmr70      --channel ETau --bcateg bb    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log --xmax 500 --ymin 1.e-5 --ymax 200  --tab --SRtype nonres --postfit --quit
python plotter.py --dir ..//analysis_ETau_10Mar_lims/ --var MT2  --sel s1b1jresolvedMcutlmr70      --channel ETau --bcateg bj    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log --xmax 500 --ymin 1.e-5 --ymax 600 --tab --SRtype nonres --postfit --quit
python plotter.py --dir ..//analysis_ETau_10Mar_lims/ --var MT2  --sel sboostedLLMcut              --channel ETau --bcateg bstbb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log --xmax 500 --ymin 1.e-5 --ymax 100 --tab --SRtype nonres --postfit --quit

python plotter.py --sigscale 10 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcutlmr90 --channel ETau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "  --ymin 5.e-4 --ymax 10 --xmax 1000 --log --tab --SRtype resLM --postfit --quit
python plotter.py --sigscale 10 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcutlmr90 --channel ETau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "  --ymin 5.e-4 --ymax 50 --xmax 1000 --log --tab --SRtype resLM --postfit --quit
python plotter.py --sigscale 1 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcuthmr90 --channel ETau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 5.e-4 --ymax 20  --xmax 1000 --log --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcuthmr90 --channel ETau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 2.e-3 --ymax 200 --xmax 1000 --log --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel sboostedLLMcut   --channel ETau --bcateg bstbb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 1.e-4 --ymax 50 --xmax 1000 --log --tab --SRtype resHM --postfit --quit


python plotter.py --dir ../analysis_TauTau_10Mar_lims/ --var MT2  --sel s2b0jresolvedMcut --channel TauTau --bcateg bb    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log  --xmax 500 --ymin 1.e-5 --ymax 800.    --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_TauTau_10Mar_lims/ --var MT2  --sel s1b1jresolvedMcut --channel TauTau --bcateg bj    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log  --xmax 500 --ymin 1.e-5 --ymax 1600.   --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_TauTau_10Mar_lims/ --var MT2  --sel sboostedLLMcut    --channel TauTau --bcateg bstbb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"   --log  --xmax 500 --ymin 1.e-5 --ymax 40.0 --tab --SRtype nonres --postfit --quit

python plotter.py --sigscale 1 --dir ../analysis_TauTau_10Mar_lims/ --var HHKin_mass_raw   --sel s2b0jresolvedMcut --channel TauTau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 1.e-4 --log  --ymax 10 --xmax 1000 --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_TauTau_10Mar_lims/ --var HHKin_mass_raw   --sel s1b1jresolvedMcut --channel TauTau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 1.e-4 --log  --ymax 100 --xmax 1000 --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_TauTau_10Mar_lims/ --var HHKin_mass_raw   --sel sboostedLLMcut    --channel TauTau --bcateg bstbb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 1.e-4 --ymax 10 --log  --xmax 1000 --tab --SRtype resHM --postfit --quit


######## linear

python plotter.py --dir ../analysis_MuTau_10Mar_lims/ --var MT2  --sel s2b0jresolvedMcutlmr70 --channel MuTau --bcateg bb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"    --xmax 500 --ymin 1.e-5    --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_MuTau_10Mar_lims/ --var MT2  --sel s1b1jresolvedMcutlmr70 --channel MuTau --bcateg bj --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"    --xmax 500 --ymin 1.e-5   --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_MuTau_10Mar_lims/ --var MT2  --sel sboostedLLMcut         --channel MuTau --bcateg bstbb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"    --xmax 500 --ymax 0.3   --tab --SRtype nonres --postfit --quit

python plotter.py --sigscale 10. --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcutlmr90 --channel MuTau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "   --xmax 1000 --ymax 5.2   --tab --SRtype resLM --postfit --xmax 600 --quit 
python plotter.py --sigscale 10. --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcutlmr90 --channel MuTau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "   --xmax 1000 --ymax 18.0  --tab --SRtype resLM --postfit --xmax 600 --quit 
python plotter.py --sigscale 1 --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcuthmr90 --channel MuTau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 5.e-3 --xmax 1000  --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcuthmr90 --channel MuTau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 5.e-3 --xmax 1000  --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 0.5 --dir ../analysis_MuTau_10Mar_lims/ --var HHKin_mass_raw  --sel sboostedLLMcut    --channel MuTau --bcateg bstbb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 0.5 pb}} "  --ymax 0.2  --xmax 1000  --tab --SRtype resHM --postfit --quit


python plotter.py --dir ..//analysis_ETau_10Mar_lims/ --var MT2  --sel s2b0jresolvedMcutlmr70      --channel ETau --bcateg bb    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"    --xmax 500 --ymin 1.e-5   --tab --SRtype nonres --postfit --quit
python plotter.py --dir ..//analysis_ETau_10Mar_lims/ --var MT2  --sel s1b1jresolvedMcutlmr70      --channel ETau --bcateg bj    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"    --xmax 500 --ymin 1.e-5  --tab --SRtype nonres --postfit --quit
python plotter.py --dir ..//analysis_ETau_10Mar_lims/ --var MT2  --sel sboostedLLMcut              --channel ETau --bcateg bstbb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"    --xmax 500 --ymax 0.15  --tab --SRtype nonres --postfit --quit

python plotter.py --sigscale 10 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcutlmr90 --channel ETau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "   --xmax 1000 --ymax 1.8 --tab --SRtype resLM --postfit --xmax 600 --quit
python plotter.py --sigscale 10 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcutlmr90 --channel ETau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 10 pb}} "   --xmax 1000 --ymax 5.5 --tab --SRtype resLM --postfit --xmax 600 --quit
python plotter.py --sigscale 1 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s2b0jresolvedMcuthmr90 --channel ETau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 5.e-4   --xmax 1000  --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel s1b1jresolvedMcuthmr90 --channel ETau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 5.e-4  --xmax 1000  --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 0.5 --dir ..//analysis_ETau_10Mar_lims/ --var HHKin_mass_raw  --sel sboostedLLMcut   --channel ETau --bcateg bstbb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 0.5 pb}} "  --ymax 0.07  --xmax 1000  --tab --SRtype resHM --postfit --quit


python plotter.py --dir ../analysis_TauTau_10Mar_lims/ --var MT2  --sel s2b0jresolvedMcut --channel TauTau --bcateg bb    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"     --xmax 500 --ymin 1.e-5  --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_TauTau_10Mar_lims/ --var MT2  --sel s1b1jresolvedMcut --channel TauTau --bcateg bj    --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"     --xmax 500 --ymin 1.e-5  --tab --SRtype nonres --postfit --quit
python plotter.py --dir ../analysis_TauTau_10Mar_lims/ --var MT2  --sel sboostedLLMcut    --channel TauTau --bcateg bstbb --lymin 0.55 --title ";m_{T2} [GeV];dN/dm_{T2} [GeV^{-1}]"     --xmax 500 --ymin 1.e-5  --tab --SRtype nonres --postfit --quit

python plotter.py --sigscale 1 --dir ../analysis_TauTau_10Mar_lims/ --var HHKin_mass_raw   --sel s2b0jresolvedMcut --channel TauTau --bcateg bb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymax 0.45    --xmax 1000 --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_TauTau_10Mar_lims/ --var HHKin_mass_raw   --sel s1b1jresolvedMcut --channel TauTau --bcateg bj --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymax 0.9    --xmax 1000 --tab --SRtype resHM --postfit --quit
python plotter.py --sigscale 1 --dir ../analysis_TauTau_10Mar_lims/ --var HHKin_mass_raw   --sel sboostedLLMcut    --channel TauTau --bcateg bstbb --lymin 0.55 --title ";m_{HH}^{KinFit} [GeV];dN/dm_{HH}^{KinFit} [GeV^{-1}]" --siglegextratext "#kern[-0.28]{#scale[0.85]{#sigma(gg#rightarrowS)#times#bf{#it{#Beta}}(S#rightarrowHH) = 1 pb}} "  --ymin 1.e-4    --xmax 1000 --tab --SRtype resHM --postfit --quit

